"""
Backward-compatible re-export shim.
New code should import from sync.core.config and sync.workflows.products.config.
"""
# Shared infrastructure config
from sync.core.config import (  # noqa: F401
    AIRTABLE_API_BASE,
    AIRTABLE_BASE_ID,
    AIRTABLE_BATCH_SIZE,
    AIRTABLE_LOG_BASE_ID,
    AIRTABLE_LOG_TOKEN,
    AIRTABLE_MAX_RETRIES,
    AIRTABLE_REQUEST_TIMEOUT,
    AIRTABLE_TEST_BASE_ID,
    AIRTABLE_TEST_TOKEN,
    AIRTABLE_TOKEN,
    LA_TIMEZONE,
    LOG_DIR,
    PRIORITY_API_URL,
    PRIORITY_MAX_CALLS_PER_MINUTE,
    PRIORITY_MAX_RETRIES,
    PRIORITY_PAGE_SIZE,
    PRIORITY_PASS,
    PRIORITY_REQUEST_TIMEOUT,
    PRIORITY_USER,
    WEBHOOK_API_KEY,
)

# Product-specific config (backward compat — these used to live here)
from sync.workflows.products.config import (  # noqa: F401
    AIRTABLE_FIELD_LAST_MODIFIED,
    AIRTABLE_FIELD_LAST_SYNCED,
    AIRTABLE_FIELD_LAST_SYNCED_FROM_PRIORITY,
    AIRTABLE_FIELD_PRIORITY_UDATE,
    AIRTABLE_FIELD_SKU,
    AIRTABLE_FIELD_SKU_WRITABLE,
    AIRTABLE_PRODUCTS_TABLE_ID,
    AIRTABLE_PRODUCTS_TABLE_NAME,
    AIRTABLE_SHELF_LIVES_TABLE_ID,
    AIRTABLE_SHELF_LIVES_VIEW,
    AIRTABLE_SYNC_VIEW,
)
